{
 "title": "Persistent Volumes Alerting",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "KAFKA 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"messaging\", persistentvolumeclaim=\"data-cluster-kafka-0\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"messaging\", persistentvolumeclaim=\"data-cluster-kafka-0\"})\n)",
     "legendFormat": "Used Space"
    }
   ]
  },
  {
   "title": "KAFKA 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"messaging\", persistentvolumeclaim=\"data-cluster-kafka-1\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"messaging\", persistentvolumeclaim=\"data-cluster-kafka-1\"})\n)",
     "legendFormat": "Used Space"
    }
   ]
  },
  {
   "title": "KAFKA 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"messaging\", persistentvolumeclaim=\"data-cluster-kafka-2\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"messaging\", persistentvolumeclaim=\"data-cluster-kafka-2\"})\n)",
     "legendFormat": "Used Space"
    }
   ]
  },
  {
   "title": "PG-History",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"pgo\", persistentvolumeclaim=\"pg-history\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"pgo\", persistentvolumeclaim=\"pg-history\"})\n)\n",
     "legendFormat": "Used Space"
    }
   ]
  },
  {
   "title": "PG-History-gkzq",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"pgo\", persistentvolumeclaim=\"pg-history-gkzq\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"pgo\", persistentvolumeclaim=\"pg-history-gkzq\"})\n)\n",
     "legendFormat": "Used Space"
    }
   ]
  },
  {
   "title": "PG-History-gxvc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"pgo\", persistentvolumeclaim=\"pg-history-gxvc\"})\n  -\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"pgo\", persistentvolumeclaim=\"pg-history-gxvc\"})\n)\n",
     "legendFormat": "Used Space"
    }
   ]
  }
 ]
}