datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true
plugins:
  - grafana-piechart-panel

rbac:
  create: true
  pspEnabled: true
serviceAccount:
  create: false
  name: grafana

replicas: 1

deploymentStrategy: 
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /var/lib/grafana/dashboards
    searchNamespace: ALL
  # configMap:
  #   name: grafana-dashboards
  
# deploymentStrategy: RollingUpdate

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10

image:
  repository: grafana/grafana
  tag: 11.1.4
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 472
  fsGroup: 472

service:
  type: LoadBalancer
  port: 80

size: 10Gi  # Specify the appropriate size for your use case

adminUser: admin
adminPassword: password

# persistence:
#   enabled: true
#   storageClassName: "prometheus"  # Specify the correct storage class
#   accessModes:
#     - ReadWriteOnce
#   

# Other configurations...

# plugins: []

